---
title: Kal Pandit's Site
author: kpandit
email: kjpandit2@ebnet.org
---
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hello!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  kjpandit2 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
