  
title: Kal Pandit's site
author: Kal Pandit
email: kjpandit2@ebnet.org

description: > # this means to ignore newlines until "baseurl:"
  Hello!

# social links
github_username: kjpandit2 # DO NOT include the @ character, or else the build will fail!

# theme
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
